Limit CircleCI Codecov upload to trusted main builds

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,21 +23,10 @@ jobs:
       - run:
           name: TypeScript coverage
           command: cd client/typescript && npm run test:coverage
-      - run:
-          name: Upload coverage to Codecov
-          command: |
-            if [ -z "${CODECOV_TOKEN:-}" ]; then
-              echo "CODECOV_TOKEN is not configured; skipping Codecov upload."
-              exit 0
-            fi
-            curl -fsSLO https://cli.codecov.io/latest/linux/codecov
-            chmod +x codecov
-            ./codecov --auto-load-params-from CircleCI upload-process \
-              -Z \
-              -t "$CODECOV_TOKEN" \
-              -C "$CIRCLE_SHA1" \
-              -f client/typescript/coverage/lcov.info \
-              --disable-search
+      - persist_to_workspace:
+          root: client/typescript
+          paths:
+            - coverage/lcov.info
       - run:
           name: TypeScript build
           command: cd client/typescript && npm run build
@@ -47,6 +36,29 @@ jobs:
       - run:
           name: Package dry run
           command: cd client/typescript && npm pack --dry-run
+
+  codecov-upload:
+    docker:
+      - image: cimg/base:stable
+    working_directory: ~/project
+    steps:
+      - attach_workspace:
+          at: ~/project/client/typescript
+      - run:
+          name: Upload coverage to Codecov
+          command: |
+            if [ -z "${CODECOV_TOKEN:-}" ]; then
+              echo "CODECOV_TOKEN is required for trusted main coverage upload."
+              exit 1
+            fi
+            curl -fsSLO https://cli.codecov.io/latest/linux/codecov
+            chmod +x codecov
+            ./codecov --auto-load-params-from CircleCI upload-process \
+              -Z \
+              -t "$CODECOV_TOKEN" \
+              -C "$CIRCLE_SHA1" \
+              -f client/typescript/coverage/lcov.info \
+              --disable-search
 
   python-package:
     docker:
@@ -78,3 +90,9 @@ workflows:
     jobs:
       - typescript-package
       - python-package
+      - codecov-upload:
+          requires:
+            - typescript-package
+          filters:
+            branches:
+              only: main
